"""review

Revision ID: 872b70e4a779
Revises: 9c649f73d768
Create Date: 2024-01-02 02:09:10.656932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872b70e4a779'
down_revision = '9c649f73d768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
